name: quick_sale
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  flutter_spinkit: ^3.1.0
  flutter_search_bar: ^2.1.0
  splashscreen:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/background.png


  fonts:
    - family: Martel_Sans
      fonts:
        - asset: fonts/Martel_Sans/MartelSans-Black.ttf
        - asset: fonts/Martel_Sans/MartelSans-ExtraLight.ttf
        - asset: fonts/Martel_Sans/MartelSans-Regular.ttf
        - asset: fonts/Martel_Sans/MartelSans-SemiBold.ttf


    - family: Open_sans
      fonts:
          - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          - asset: fonts/Open_Sans/OpenSans-Light.ttf
          - asset: fonts/Open_Sans/OpenSans-Regular.ttf
          - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf

